<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[2]=array(0,-8,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[3]=array(0,-8,1,'6LWE6K6v5Lit5b+D');
$cfg_Cs[4]=array(0,-8,1,'5Lqn5ZOB5Lit5b+D');
$cfg_Cs[5]=array(0,-8,1,'5qGI5L6L5bGV56S6');
$cfg_Cs[6]=array(0,-8,1,'6KeG6aKR5bGV56S6');
$cfg_Cs[7]=array(0,-8,1,'5oub5ZWG5Yqg55uf');
$cfg_Cs[8]=array(0,-8,1,'6IGU57O75oiR5Lus');
$cfg_Cs[15]=array(3,1,1,'5paw6Ze7MQ==');
$cfg_Cs[14]=array(2,1,1,'5YWs5Y+4566A5LuL');
$cfg_Cs[17]=array(3,-8,1,'5paw6Ze7Mg==');
$cfg_Cs[18]=array(5,-8,1,'5qGI5L6LMQ==');
$cfg_Cs[19]=array(4,1,1,'5Lqn5ZOBMQ==');
$cfg_Cs[20]=array(6,1,1,'6KeG6aKRMQ==');
?>