<li>
                    <h1>{dede:field name='typename'/}</h1>
                    <div class="InfoContent">
                        <div>
                            <video controls="controls" style=" width:100%; ">
                                <source src={dede:field.content/} type="video/mp4" /> 你的浏览器不支持H5播放器;
                            </video>
                        </div>
                    </div>
                </li>