<?php
$z[0]=Array("channelartlist","\r\n                <li>\r\n                    <h1>{dede:field name='typename'/}</h1>\r\n                    <div class=\"InfoContent\">\r\n                        <div>\r\n                            <video controls=\"controls\" style=\" width:100%; \">\r\n                                <source src={dede:field.content/} type=\"video/mp4\" /> 你的浏览器不支持H5播放器;\r\n                            </video>\r\n                        </div>\r\n                    </div>\r\n                </li>\r\n                ",4655,5200);
$z[0][4]=array();

?>